---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: jenkins
  name: jenkins-admin-george
  namespace: george

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: jenkins-admin-george
subjects:
  - kind: ServiceAccount
    name: jenkins-admin-george
    namespace: george
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin #TODO: This is too open
